export enum AUTH_ACTIONS {
  SET_USER_DATA = 'AUTH@SET_USER_DATA',
  LOADING_USER_DATA = 'AUTH@LOADING_USER_DATA',
  SET_TOKEN = 'AUTH@SET_TOKEN',
  CLEAR_ALL = 'AUTH@CLEAR_ALL',
  SET_IS_AUTHENTICATED = 'AUTH@SET_IS_AUTHENTICATED'
}
